name: Docker Image CI

on:
  release:
    types: [published]



jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RABBITMQ_SERVER: ${{ secrets.RABBITMQ_SERVER }}
      RABBITMQ_USER: jadjer
      RABBITMQ_PASS: Alchogol01
      SMS_API_HOST: http://192.168.1.1
      SMS_API_USER:
      SMS_API_PASS:

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image with $RABBITMQ_SERVER
        run: docker build . --tag sms_manager -e RABBITMQ_SERVER=$RABBITMQ_SERVER -e RABBITMQ_USER=$RABBITMQ_USER -e RABBITMQ_PASS=$RABBITMQ_PASS -e SMS_API_HOST=SMS_API_HOST

  deployment:
    name: Push Docker image to Docker Hub
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Deploy the docker image
        run: docker push ${{ secrets.DOCKER_USER }}/ride2online_sms_manager
